### ISSUE TITLE
Rename geocompr to geocompx

### ISSUE THREAD

**Issue by Nowosad** [geocompx/docker#38]
Hi @Robinlovelace -- are there any plans to rename images from geocompr to geocompx?

**Comment by Robinlovelace** [comment]
Good question, not yet but we could make some.

**Comment by Robinlovelace** [comment]
Most of the guidance already contains geocompx not geocompr, e.g.

https://github.com/geocompx/docker/blob/75e7c681daf6083765cbece125d7cab465360234/README.Rmd#L26

Any other places we should make the change? In terms of Docker Hub names, no plan to change things.
