### ISSUE TITLE
Saga plugin installation steps causing Docker build to fail

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/docker#41]
With the following message:

```
Dockerfile:48
--------------------
  46 |     RUN sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/qgis-archive-keyring.gpg] https://qgis.org/ubuntugis `lsb_release -c -s` main" > /etc/apt/sources.list.d/qgis.list'
  47 |     RUN apt-get update
  48 | >>> RUN apt-get install -y qgis qgis-plugin-grass saga
  49 |     RUN wget -qO sagang_plugin.zip https://plugins.qgis.org/plugins/processing_saga_nextgen/version/0.0.7/download/
  50 |     RUN unzip -q sagang_plugin.zip -d /home/rstudio/.local/share/QGIS/QGIS3/profiles/default/python/plugins
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get install -y qgis qgis-plugin-grass saga" did not complete successfully: exit code: 100
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c apt-get install -y qgis qgis-plugin-grass saga" did not complete successfully: exit code: 100
```

Source: https://github.com/geocompx/docker/actions/runs/6321057960/job/17164486628#step:8:644

Relevant lines: 

https://github.com/geocompx/docker/blob/00f4c906b6827454b9c7cc1498a8782246688449/qgis/Dockerfile#L48-L50

Any ideas @jannes-m ?

**Comment by florisvdh** [comment]
> the ubuntugis-nightly-release repo, which is much quicker at levelling up with the PPA

But I think you'll have to wait a little longer; latest build there is 2023-09-23. https://ubuntu.qgis.org/ubuntu-nightly/pool/main/q/qgis/?C=M;O=D

**Comment by jannes-m** [comment]
I am trying to build the image locally at the moment. And as @nyalldawson already mentionend, SAGA is not the problem. Instead an incompatible version of GRASS should be installed as already suspected by @florisvdh. Currently, I am using ubuntugis-nightly-release repo, let's see if this works out, probably not if the latest build is 2023-09-23. In any case, to avoid this issue in the future, let's switch to the ubuntugis-nightly-release.

**Comment by jannes-m** [comment]
Locally, I could successfully build the container, so closing via 815c5a2.

**Comment by florisvdh** [comment]
> latest build there is 2023-09-23. https://ubuntu.qgis.org/ubuntu-nightly/pool/main/q/qgis/?C=M;O=D

I was looking in the wrong place here; that's the URL of Ubuntu-nightly, built is against the Ubuntu GDAL etc, not against the PPA.  Of course the URL must be https://ubuntugis.qgis.org/ubuntugis-nightly-release/pool/main/q/qgis/?C=M;O=D. Latest build there is from 2023-09-24 17:12 which indeed appears to work with current GRASS already :rocket: .

**Comment by Robinlovelace** [comment]
Great job all, just checking this after busy day, stoked to see it's fixed. Thank you!
