### ISSUE TITLE
qgis image failing

### ISSUE THREAD

**Issue by Robinlovelace** [geocompx/docker#44]
As shown here

![image](https://github.com/geocompx/docker/assets/1825120/71117b7b-44de-4ad9-a080-fcd2e5a6b9dd)

Related: https://github.com/geocompx/docker/commit/b5c58cef7f1b8b1d5fb188f1e5e4af92978d869a#commitcomment-138984633

**Comment by Robinlovelace** [comment]
Not sure what the issue is but sounds like it may be fixed upstream as per conversation with @jannes-m

**Comment by jannes-m** [comment]
Yeah, I'll take care of it

**Comment by Robinlovelace** [comment]
Thanks Jannes.

**Comment by jannes-m** [comment]
closed via 60f5669a76dcffdcdb0284d418d99ac32c8403ea
